### ISSUE TITLE
not pushing log_message, only exceptions are being pusdh

### ISSUE THREAD

**Issue by shantiwebsolution** [Terrorboy/CodeIgniter4-sentry#1]
With this lib,

only CI exceptions are being pushed to Sentry.
Any log via log_message function is not being pushed to Sentry.
How that could be possible ?

**Comment by Terrorboy** [comment]
https://github.com/Terrorboy/CodeIgniter4-sentry/blob/master/app/ThirdParty/Sentry.php

please replace the file(has been updated)
