### ISSUE TITLE
ErrorException: Module 'intl' already loaded

### ISSUE THREAD

**Issue by shantiwebsolution** [Terrorboy/CodeIgniter4-sentry#2]
ErrorException being thrown at line \Sentry\captureLastError();

**Comment by shantiwebsolution** [comment]
Following exception is also being thrown by lib

Sentry\Exception\FatalErrorException
Core Warning: Module 'intl' already loaded

**Comment by Terrorboy** [comment]
The problem seems to be with 'sentry/sdk'
Could you please check the version of sentry/sdk and register an issue at https://github.com/getsentry/sentry-php

First, check whether the server's intl setting is normal.

**Comment by shantiwebsolution** [comment]
Sure I have done.
Let's see what they reply https://github.com/getsentry/sentry-php/issues/1237#issue-981091010
